/**
 * National code mapping for country display
 * Reference: closet-design-system packages/web/src/constants/nationalCode.ts
 */
export const NATIONAL_CODE_MAP: Record<string, string> = {
  KR: '대한민국',
  US: '미국',
  JP: '일본',
  CN: '중국',
  GB: '영국',
  FR: '프랑스',
  DE: '독일',
  IT: '이탈리아',
  ES: '스페인',
  AU: '호주',
  CA: '캐나다',
  BR: '브라질',
  IN: '인도',
  RU: '러시아',
  TH: '태국',
  VN: '베트남',
  ID: '인도네시아',
  MY: '말레이시아',
  SG: '싱가포르',
  TW: '대만',
  HK: '홍콩',
  NL: '네덜란드',
  SE: '스웨덴',
  NO: '노르웨이',
  DK: '덴마크',
  FI: '핀란드',
  PL: '폴란드',
  TR: '터키',
  MX: '멕시코',
  AR: '아르헨티나',
  CL: '칠레',
  CO: '콜롬비아',
  PH: '필리핀',
  NZ: '뉴질랜드',
  AE: '아랍에미리트',
  SA: '사우디아라비아',
  EG: '이집트',
  ZA: '남아프리카공화국',
  PT: '포르투갈',
  BE: '벨기에',
  AT: '오스트리아',
  CH: '스위스',
  GR: '그리스',
  IE: '아일랜드',
  CZ: '체코',
  HU: '헝가리',
  RO: '루마니아',
  UA: '우크라이나',
  IL: '이스라엘',
  PK: '파키스탄',
  BD: '방글라데시',
  NG: '나이지리아',
  KE: '케냐',
  GH: '가나',
  ET: '에티오피아',
  OTHER: '기타',
};

export const getNationalName = (code: string): string => {
  return NATIONAL_CODE_MAP[code] || code || '알 수 없음';
};
